
import React, { Component } from 'react';
import dynamic from 'next/dynamic'
import Head from 'next/head';
const TextEditor = dynamic(import('../components/textEditor'), {
  ssr: false
})
export default function IndexPage() {
  return (
    <div>
        <Head>
        <title>home page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
	       <TextEditor lan='json' theme="twilight"/>
          </div>
  );
}
